### ISSUE TITLE
swagger-zod produces wrong tuple syntax

### ISSUE THREAD

**Issue by helt** [kubb-labs/kubb#1018]
### What version of `kubb` is running?

HEAD

### What platform is your computer?

WSL

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

-

### What steps can reproduce the bug?

According to my understanding of the [zod spec, tuples do not support `min` and `max`](https://zod.dev/?id=tuples). Hence, the schema snippet below produces invalid syntax. My IDE also concludes the same:
![image](https://github.com/kubb-labs/kubb/assets/1732112/2668d67b-166c-4523-83f0-0e6eeaf7aa1a)

schema:
```
    PetTuple:
      maxItems: 2
      minItems: 2
      prefixItems:
        - type: string
        - type: string
      title: Attributes
      type: array
      description: Tuple of exact length 2
```

produces
```ts
export const petTuple = z.tuple([z.string(), z.string()]).min(2).max(2)
```

### How often does this bug happen?

None

### What is the expected behavior?

```ts
export const petTuple = z.tuple([z.string(), z.string()])
```

### Additional information

See #1017
