### ISSUE TITLE
Invalid code generated by @kubb/swagger-zod

### ISSUE THREAD

**Issue by Flixbox** [kubb-labs/kubb#1091]
### What version of `kubb` is running?

"@kubb/cli": "2.23.3",     "@kubb/core": "2.23.3",     "@kubb/plugin-oas": "2.23.3",     "@kubb/react": "2.23.3",     "@kubb/swagger-client": "2.23.3",     "@kubb/swagger-tanstack-query": "2.23.3",     "@kubb/swagger-ts": "2.23.3",     "@kubb/swagger-zod": "2.23.3"

### What platform is your computer?

Linux (WSL2/Ubuntu 20 LTS)

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

"zod": "3.23.8", "typescript": "5.4.5"

### What steps can reproduce the bug?

Upon running `npx kubb` it generates 50+ fully functioning validators, however 2 validators are generated with invalid syntax.

Formatted:

```ts
import { z } from 'zod';

import { enumerationValueSpecificationDtoSchema } from './enumerationValueSpecificationDtoSchema';
import { rangeValueSpecificationDtoSchema } from './rangeValueSpecificationDtoSchema';
import { regexValueSpecificationDtoSchema } from './regexValueSpecificationDtoSchema';
import { sliderValueSpecificationDtoSchema } from './sliderValueSpecificationDtoSchema';

export const valueSpecificationDtoSchema = z.union([
    z.lazy(() => enumerationValueSpecificationDtoSchema),
    z.lazy(() => rangeValueSpecificationDtoSchema),
    z.lazy(() => regexValueSpecificationDtoSchema),
    z.lazy(() => sliderValueSpecificationDtoSchema),
  ]),
  z,
  object;
({ type: z.enum(['enum', 'range', 'regex', 'slider']) });
```

Errors during build:

```
[tsc] src/_generated/planning-api/zod/valueSpecificationDtoSchema.ts(1,10): error TS2395: Individual declarations in merged declaration 'z' must be all exported or all local.
[tsc] src/_generated/planning-api/zod/valueSpecificationDtoSchema.ts(1,10): error TS2440: Import declaration conflicts with local declaration of 'z'.
[tsc] src/_generated/planning-api/zod/valueSpecificationDtoSchema.ts(8,44): error TS2448: Block-scoped variable 'z' used before its declaration.
[tsc] src/_generated/planning-api/zod/valueSpecificationDtoSchema.ts(9,5): error TS2448: Block-scoped variable 'z' used before its declaration.
[tsc] src/_generated/planning-api/zod/valueSpecificationDtoSchema.ts(10,5): error TS2448: Block-scoped variable 'z' used before its declaration.
[tsc] src/_generated/planning-api/zod/valueSpecificationDtoSchema.ts(11,5): error TS2448: Block-scoped variable 'z' used before its declaration.
[tsc] src/_generated/planning-api/zod/valueSpecificationDtoSchema.ts(12,5): error TS2448: Block-scoped variable 'z' used before its declaration.
[tsc] src/_generated/planning-api/zod/valueSpecificationDtoSchema.ts(14,3): error TS1155: 'const' declarations must be initialized.
[tsc] src/_generated/planning-api/zod/valueSpecificationDtoSchema.ts(14,3): error TS2395: Individual declarations in merged declaration 'z' must be all exported or all local.
[tsc] src/_generated/planning-api/zod/valueSpecificationDtoSchema.ts(14,3): error TS7005: Variable 'z' implicitly has an 'any' type.
[tsc] src/_generated/planning-api/zod/valueSpecificationDtoSchema.ts(15,3): error TS1155: 'const' declarations must be initialized.
[tsc] src/_generated/planning-api/zod/valueSpecificationDtoSchema.ts(15,3): error TS7005: Variable 'object' implicitly has an 'any' type.
```

### How often does this bug happen?

Every time

### What is the expected behavior?

The generated code should compile.

### Swagger/OpenAPI file?

I can provide a full file upon request. Here's the part that causes the issue:

```yaml
    ValueSpecificationDto:
      title: ValueSpecification
      required:
        - type
      type: object
      oneOf:
        - $ref: "#/components/schemas/EnumerationValueSpecificationDto"
        - $ref: "#/components/schemas/RangeValueSpecificationDto"
        - $ref: "#/components/schemas/RegexValueSpecificationDto"
        - $ref: "#/components/schemas/SliderValueSpecificationDto"
      properties:
        type:
          minLength: 1
          enum:
            - enum
            - range
            - regex
            - slider
          type: string
          readOnly: true
      additionalProperties: false
      discriminator:
        propertyName: type
        mapping:
          enum: "#/components/schemas/EnumerationValueSpecificationDto"
          range: "#/components/schemas/RangeValueSpecificationDto"
          regex: "#/components/schemas/RegexValueSpecificationDto"
          slider: "#/components/schemas/SliderValueSpecificationDto"
```

### Additional information

kubb config:

```ts
import { defineConfig } from '@kubb/core'
import { pluginOas } from '@kubb/plugin-oas'
import { pluginZod } from '@kubb/swagger-zod'

const generateDefaultConfig = (nameOverride?: string) => ({
  root: '.',
  plugins: [
    pluginOas({}),
    pluginZod({}),
  ],
})

export default defineConfig(() => {
  return [
    {
      ...generateDefaultConfig(),
      input: {
        path: './openapi/PlanningAPI.yaml',
      },
      output: {
        path: './src/_generated/planning-api',
        clean: true,
      },
    }
  ]
})
```

[Thread in Discord](https://discord.com/channels/1117538769235615835/1266280440801525791/1266280440801525791)

**Comment by stijnvanhulle** [comment]
@Flixbox Can you provide me the schema of `EnumerationValueSpecificationDto`, `RangeValueSpecificationDto`, `RegexValueSpecificationDto` and `SliderValueSpecificationDto`? I need to see what is inside that to know what is going wrong.

**Comment by Flixbox** [comment]
```
    EnumerationValueSpecificationDto:
      title: EnumerationValueSpecification
      required:
        - enumeration
        - type
      type: object
      properties:
        type:
          minLength: 1
          type: string
          readOnly: true
        enumeration:
          type: array
          items: {}
      additionalProperties: false
```

```
    RangeValueSpecificationDto:
      title: RangeValueSpecification
      required:
        - max
        - min
        - type
      type: object
      properties:
        type:
          minLength: 1
          type: string
          readOnly: true
        min:
          type: number
          format: float
        max:
          type: number
          format: float
      additionalProperties: false
```

```
    RegexValueSpecificationDto:
      title: RegexValueSpecification
      required:
        - regex
        - type
      type: object
      properties:
        type:
          minLength: 1
          type: string
          readOnly: true
        regex:
          minLength: 1
          type: string
      additionalProperties: false
```

```
    SliderValueSpecificationDto:
      title: SliderValueSpecification
      required:
        - left_text
        - max_value
        - right_text
        - type
      type: object
      properties:
        type:
          minLength: 1
          type: string
          readOnly: true
        left_text:
          $ref: "#/components/schemas/LocalizedTextDto"
        right_text:
          $ref: "#/components/schemas/LocalizedTextDto"
        max_value:
          type: integer
          format: int32
      additionalProperties: false
```

```
    LocalizedTextDto:
      title: LocalizedText
      required:
        - default_text
        - text_id
      type: object
      properties:
        text_id:
          minLength: 1
          type: string
        default_text:
          minLength: 1
          type: string
      additionalProperties: false
```
