### ISSUE TITLE
@kubb/plugin-ts: Discriminator parsing error: "Cannot read properties of undefined (reading 'enum')"

### ISSUE THREAD

**Issue by telmofcosta** [kubb-labs/kubb#1669]
### What version of `kubb` is running?

3.10.0

### What kind of platform do you use?

MacOS

### Your `kubb.config.ts` config file?

```typescript
import { defineConfig } from '@kubb/core';
import { pluginOas } from '@kubb/plugin-oas';
import { pluginTs } from '@kubb/plugin-ts';

export default defineConfig({
  input: {
    path: './schema.yaml',
  },
  output: {
    extension: { '.ts': '' },
    clean: true,
    path: './src',
  },
  plugins: [
    pluginOas({
      validate: true,
      // @ts-ignore
      output: false,
    }),
    pluginTs({
      output: {
        path: './types',
      },
      exclude: [],
      enumType: 'asConst',
      unknownType: 'void',
      optionalType: 'questionToken',
      oasType: false,
    }),
  ],
});
```

### Swagger/OpenAPI file?

```bash
---
openapi: 3.0.3
info:
  title: Kubb discriminator test
  version: v1
paths:
  "/api/animals/{animal}":
    get:
      tags:
      - Animals
      parameters:
      - name: animal
        in: path
        schema:
          type: string
          enum: [dog, bird]
        required: true
      responses:
        '200':
          description: Gets an animal
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Animal"
components:
  schemas:
    Animal:
      oneOf:
        - "$ref": "#/components/schemas/Dog"
        - "$ref": "#/components/schemas/Bird"
      discriminator:
        propertyName: name
        mapping:
          dog: "#/components/schemas/Dog"
          bird: "#/components/schemas/Bird"
    Dog:
      type: object
      properties:
        name:
          type: string
        runningSpeed:
          type: integer
      required:
        - name
        - runningSpeed
    Bird:
      type: object
      properties:
        name:
          type: string
        wingSpan:
          type: integer
      required:
        - name
        - wingSpan
```

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

```JSON
{
  "name": "kubb_test",
  "version": "1.0.0",
  "description": "",
  "engines": {
    "node": "v20.12.2",
    "pnpm": "9.0.4"
  },
  "scripts": {
    "schema:generate": "kubb generate"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@kubb/cli": "3.10.0",
    "@kubb/core": "3.10.0",
    "@kubb/plugin-oas": "3.10.0",
    "@kubb/plugin-react-query": "3.10.0",
    "@kubb/plugin-ts": "3.10.0",
    "typescript": "5.3.3"
  }
}
```

### What steps can reproduce the bug?

Run `kubb generate`

### How often does this bug happen?

Every time

### Additional information

The problem appears when parsing the discriminator.
The above schema works on version 3.9.5.

I can make it work, but I need to add some extra properties to the schema that contains the discriminator:
```yaml
components:
  schemas:
    Animal:
      oneOf:
        - "$ref": "#/components/schemas/Dog"
        - "$ref": "#/components/schemas/Bird"
      discriminator:
        propertyName: name
        mapping:
          dog: "#/components/schemas/Dog"
          bird: "#/components/schemas/Bird"
      properties:
        name:
          type: string
          enum:
            - dog
            - bird
      required:
        - name
```
☝ This now works fine.

According to the specs, the list of properties with the enum is unnecessary, but the code requires it (thus the error). The enum can be inferred using the keys of the mapping:
```yaml
mapping:
  dog: "#/components/schemas/Dog"
  bird: "#/components/schemas/Bird"
```

And also according to the specs, even the mapping is not necessary, and the enum can be inferred by the schemas' names:
```yaml
    Animal:
      oneOf:
      - "$ref": "#/components/schemas/Dog"
      - "$ref": "#/components/schemas/Bird"
      discriminator:
        propertyName: name
```
In this example, we can infer that `name` can be either `Dog` or `Bird`.

There is a second problem (that also affects earlier versions). The discriminator can be used with either `anyOf` or `oneOf`, but the current implementation does not work well with `anyOf`:
```ts
// With oneOf
export const animalNameEnum = {
  dog: 'dog',
  bird: 'bird',
} as const;

export type AnimalNameEnum = (typeof animalNameEnum)[keyof typeof animalNameEnum];

export type Animal =
  | (Dog & {
      /**
       * @type string
       */
      name: AnimalNameEnum;
    })
  | (Bird & {
      /**
       * @type string
       */
      name: AnimalNameEnum;
    });

``` 

```ts
// With anyOf
export const animalNameEnum = {
  dog: 'dog',
  bird: 'bird',
} as const;

export type AnimalNameEnum = (typeof animalNameEnum)[keyof typeof animalNameEnum];

export type Animal = {
  /**
   * @type string
   */
  name: AnimalNameEnum;
};
``` 

Specs: https://swagger.io/docs/specification/v3_0/data-models/inheritance-and-polymorphism/#discriminator

**Comment by telmofcosta** [comment]
Sorry for sounding annoying, that's not my purpose 😅 

We have a schema that is not parsed correctly by the current implementation. Here's a simple example:
```yaml
components:
  schemas:
    Animal:
      anyOf:
      - "$ref": "#/components/schemas/Dog"
      - "$ref": "#/components/schemas/Cat"
      discriminator:
        propertyName: name
        mapping:
          bulldog: "#/components/schemas/Dog"
          labrador: "#/components/schemas/Dog"
          ragdoll: "#/components/schemas/Cat"
    Dog:
      type: object
      properties:
        name:
          type: string
        bark:
          type: string
      required:
        - name
        - bark
    Cat:
      type: object
      properties:
        name:
          type: string
        meow:
          type: string
      required:
        - name
        - meow
```

The current implementation assumes a 1-1 relationship between each key on the mapping and a schema, while in my example, both bulldog and labrador map to the same schema.

Current behaviour:
```ts
import type { Cat } from './Cat'
import type { Dog } from './Dog'

export type Animal =
  | (Dog & { name: 'bulldog' })
  | (Cat & { name: 'ragdoll' })
```

Expected behaviour:
```ts
import type { Cat } from './Cat'
import type { Dog } from './Dog'

export type Animal =
  | (Dog & { name: 'bulldog' })
  | (Dog & { name: 'labrador' })
  | (Cat & { name: 'ragdoll' })
```

In your defence, the [discriminator spec](https://spec.openapis.org/oas/v3.1.1.html#discriminator-object) defines it very loosely, which makes it hard to map it to TypeScript while keeping all the spec covered.
