### ISSUE TITLE
[swagger-zod] `date` format properties are incorrectly validated using `.datetime()`

### ISSUE THREAD

**Issue by aburgel** [kubb-labs/kubb#944]
### What version of `kubb` is running?

kubb/2.13.0 darwin-arm64 node-v20.11.1

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

zod:  3.22.4

### What steps can reproduce the bug?

OpenAPI schema:
```yaml
    Object:
      type: object
      properties:
        date_of_birth:
          type: string
          format: date
```

zod schema:
```typescript
export const objectSchema = z.object({ "date_of_birth": z.string().datetime({ offset: true }) });
```

kubb.config.js:
```typescript
    plugins: [
      ...
      [
        "@kubb/swagger-zod",
        {
          dateType: "stringOffset",
          output: {
            path: "./zod",
          },
        },
      ],
      ...
   ]
```

### How often does this bug happen?

Every time
