### ISSUE TITLE
Optional signal not being considered when using nullable

### ISSUE THREAD

**Issue by vitorcamachoo** [kubb-labs/kubb#972]
If a property in Swagger is both nullable and optional, the generator skips the optional signal in the output TypeScript models.

Input:
```yaml
User:
      type: object
      properties:
        defaultProject:
          type: string
          format: uuid
          nullable: true
```

Output:
```ts
export type User = {
  /**
   * @type string, uuid
   */
  defaultProject: string | null
}
```

Expected Output:
```ts
export type User = {
  /**
   * @type string, uuid
   */
  defaultProject?: string | null
}
```

Is this the intended behaviour?

_Originally posted by @vitorcamachoo in https://github.com/kubb-labs/kubb/issues/930#issuecomment-2072972548_
