### ISSUE TITLE
Common parameters in path stopped generating correctly with TS in 2.16.1 

### ISSUE THREAD

**Issue by g-gagnon** [kubb-labs/kubb#973]
### What version of `kubb` is running?

kubb/2.16.2 darwin-arm64 node-v20.10.0

### What platform is your computer?

MacOS

### What steps can reproduce the bug?

When using [common parameter](https://swagger.io/docs/specification/describing-parameters/#common) in paths, they are not generated properly in the resulting TS. I tested with 2.16.0 and it worked, so it might be a changed introduced in 2.16.1.

### How often does this bug happen?

None

### What is the expected behavior?

Given

```
paths:
  /user/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: The user ID
    get:
      # ...
    post:
      # ...
```

I'd expect my `getUser()` function to have a `id` argument of `GetUserPathParams["id"]`. Right now it is not present. If I put the `parameters` section inside the get block, it works correctly.
